services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411" # Zipkin UI 접근 포트

  # Redis 마스터 노드 1
  redis-master1:
    image: redis:7
    container_name: redis-master1
    command: ["redis-server", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "systempass"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data_master1:/data
    networks:
      - redis-cluster

  # Redis 마스터 노드 2
  redis-master2:
    image: redis:7
    container_name: redis-master2
    command: ["redis-server", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "systempass"]
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data_master2:/data
    networks:
      - redis-cluster

  # Redis 마스터 노드 3
  redis-master3:
    image: redis:7
    container_name: redis-master3
    command: ["redis-server", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "systempass"]
    ports:
      - "6381:6379"
    volumes:
      - ./redis_data_master3:/data
    networks:
      - redis-cluster

  # Redis 슬레이브 노드 1
  redis-slave1:
    image: redis:7
    container_name: redis-slave1
    command: ["redis-server", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "systempass", "--masterauth", "systempass"]
    ports:
      - "6382:6379"
    volumes:
      - ./redis_data_slave1:/data
    networks:
      - redis-cluster

  # Redis 슬레이브 노드 2
  redis-slave2:
    image: redis:7
    container_name: redis-slave2
    command: ["redis-server", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "systempass", "--masterauth", "systempass"]
    ports:
      - "6383:6379"
    volumes:
      - ./redis_data_slave2:/data
    networks:
      - redis-cluster

  # Redis 슬레이브 노드 3
  redis-slave3:
    image: redis:7
    container_name: redis-slave3
    command: ["redis-server", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "systempass", "--masterauth", "systempass"]
    ports:
      - "6384:6379"
    volumes:
      - ./redis_data_slave3:/data
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
