services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411" # Zipkin UI에 접근할 포트
    networks:
      - eureka-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    networks:
      - eureka-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker-config/prometheus.yml:/etc/prometheus/prometheus.yml  # 상대 경로 수정
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - eureka-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - eureka-network

networks:
  eureka-network:
    external: true  # eureka-network를 외부 네트워크로 설정