services:

  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=fortickets'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=forman'
    ports:
      - '54323:5432'
    volumes:
      - ../db/concert-service:/var/lib/postgresql/data


  concert-service:
    container_name: concert-service
    build:
      context: ../application/concert-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - '11000:11000'
    restart: always
    depends_on:
      - postgres-conert
    volumes:
      - ../logs/concertservice:/logs/concertservice
    networks:
      - service-network