spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  security:
    csrf:
      enabled: false  # CSRF 보호 비활성화
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        - id: concert-service
          uri: lb://concert-service
          predicates:
            - Path=/concert-service/**
          filters:
            - RewritePath=/concert-service/(?<segment>.*), /${segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /${segment}

server:
  port: 12011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12001/eureka/

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"