services:

  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=fortickets'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=forman'
    ports:
      - '54321:5432'
    volumes:
      - ../db/order-service:/var/lib/postgresql/data

