spring:
  application:
    name: eureka-server
  profiles:
    default: dev
server:
  port: 12001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:12001/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
